### ISSUE TITLE
error creating sensor

### ISSUE THREAD

**Issue by beckspaced** [klaubert/waf-fle#21]
hello there ;-)

first of all thanks a lot for waf-fle!

installed it on an opensuse 13.1 box with apache 2.4.6, php 5.4.20 and modsecurity 2.6.7 with CRS 2.2.5

installed waf-fle according to the setup instructions and all went sort of fine, but when trying to create a sensor the following error come up. the sensor was created without the checkbox use client IP from header and an empty input field for that option

HTTP/1.1 500 Internal Server Error Error (saveSensor) Message: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: '' for column 'client_ip_via' at row 1 Error (saveSensor) getTraceAsString: #0 /srv/ssl/waffle/waffle/functions.php(2502): PDOStatement->execute() #1 /srv/ssl/waffle/waffle/dashboard/management.php(173): saveSensor('new', 'sensor', NULL, 'description', 1, '123456', false, NULL) #2 {main} 

if i create a sensor and fill in ALL fields, an check the box use client IP from header with an input field value of X-Forwarded-For then no error triggers and the sensor is stored in the database ...

how can i fix this?

thanks & greetings
becki

**Comment by garoldalahai12** [comment]
![image](https://user-images.githubusercontent.com/32946200/34402952-0e4a5fa6-ebe0-11e7-885a-cc1fa41e6db2.png)

HTTP/1.1 500 Internal Server Error Error (saveSensor) Message: SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'client_ip_via' at row 1 Error (saveSensor) getTraceAsString: #0 /usr/local/waf-fle/functions.php(2500): PDOStatement->execute() #1 /usr/local/waf-fle/dashboard/management.php(173): saveSensor('new', 'Waf-test', '192.168.26.23', 'test3', 1, 'waftest123', false, NULL) #2 {main} 

Can sombody help me ?? 
Thank you :)

**Comment by garoldalahai12** [comment]
HTTP/1.1 500 Internal Server Error Error (saveSensor) Message: SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'client_ip_via' at row 1 Error (saveSensor) getTraceAsString: #0 /usr/local/waf-fle/functions.php(2500): PDOStatement->execute() #1 /usr/local/waf-fle/dashboard/management.php(173): saveSensor('new', 'Waf-test', '192.168.26.23', 'test3', 1, 'waftest123', false, NULL) #2 {main} 

Can somebody help me
Thanks, :D
