### ISSUE TITLE
Failed to send the Log

### ISSUE THREAD

**Issue by wangxianwei** [klaubert/waf-fle#30]
Hi All,
I have installed the waf-fle in a  server. So I can vist the http://192.168.9.162/waf-fle/login.php, I have got the following info after config the sensor.            

-- Audit log configuration -------------------------------------------------
#Log the transactions that are marked by a rule, as well as those that
# trigger a server error (determined by a 5xx or 4xx, excluding 404,
#level response status codes).
#
SecAuditEngine RelevantOnly
SecAuditLogRelevantStatus "^(?:5|4(?!04))"
# Log everything we know about a transaction.
SecAuditLogParts ABIDEFGHZ
SecAuditLogType Concurrent
SecAuditLog "|/usr/local/bin/mlogc /etc/mlogc.conf" 
->The value that I have changed in the Modsecurity.conf according the folder which the mlogc installed 
# Specify the path for concurrent audit logging.
SecAuditLogStorageDir  /log/modsecurity/data
# ... Continue with your current modsecurity.conf

Using the following command to inactive the mlogc:
./mlogc-batch-load.pl /log/modsecurity/data /usr/local/modsecurity/bin/mlogc /etc/mlogc.conf

The erro info in the error mlogc-error.log :

[Wed Jan 28 08:58:25 2015] [3] [30569/0] Configuring ModSecurity Audit Log Collector 2.9.0-RC2.
[Wed Jan 28 08:58:25 2015] [3] [30569/0] Delaying execution for 5000ms.
[Wed Jan 28 08:58:32 2015] [3] [30569/0] Loaded 10948 entries from the queue file.
[Wed Jan 28 08:58:32 2015] [2] [30569/7f8d140009c0] Invalid entry (failed to match regex): SZ-TEST-RD01 192.168.1.250 - - [19/Jan/2015:17:08:19 +0800] \"POST /communication/getPartnerInfo.do HTTP/1.1\" - 186 \"http://www.352.com/\" \"-\" AcAcAcJJkcAcAcA1A@AcMcAg \"-\" /20150119/20150119-1708/20150119-170819-AcAcAcJJkcAcAcA1A@AcMcAg 0 1576 md5:90f7408c67e767c785a7c36f4cf4cb72
[Wed Jan 28 08:58:32 2015] [2] [30569/7f8d140009c0] Invalid entry (failed to match regex): SZ-TEST-RD01 192.168.1.250 - - [19/Jan/2015:17:12:37 +0800] \"POST /communication/getPartnerInfo.do HTTP/1.1\" - 186 \"http://www.352.com/information/financing_list.jsp?type=%E8%B5%84%E4%BA%A7&typeName=%E6%94%B6%E8%B4%B9%E6%9D%83\" \"-\" AcocAcbc6cAcKcAyAcAcAcAc \"-\" /20150119/20150119-1712/20150119-171237-AcocAcbc6cAcKcAyAcAcAcAc 0 1710 md5:274199c512e5a369bc2139bacc073bb7
[Wed Jan 28 08:58:32 2015] [2] [30569/7f8d140009c0] Invalid entry (failed to match regex): SZ-TEST-RD01 192.168.1.250 - - [19/Jan/2015:17:12:37 +0800] \"POST /common/memberLogin.jsp HTTP/1.1\" - 186 \"http://www.352.com/information/financing_list.jsp?type=%E8%B5%84%E4%BA%A7&typeName=%E6%94%B6%E8%B4%B9%E6%9D%83\" \"-\" Acac@cABAcjxAsAcBcAcjcAc \"-\" /20150119/20150119-1712/20150119-171237-Acac@cABAcjxAsAcBcAcjcAc 0 1781 md5:62fc43657f77210ec82b415784430155
[Wed Jan 28 08:58:32 2015] [2] [30569/7f8d140009c0] Invalid entry (failed to match regex): SZ-TEST-RD01 192.168.1.250 - - [19/Jan/2015:17:12:13 +0800] \"POST /communication/getPartnerInfo.do HTTP/1.1\" - 186 \"http://www.352.com/\" \"-\" AnAcAcAyAcAcAcAwAcAcAhA5 \"-\" /20150119/20150119-1712/20150119-171213-AnAcAcAyAcAcAcAwAcAcAhA5 0 1599 md5:45b812fe3048c79a14b4524d7e4976c9
[Wed Jan 28 08:58:32 2015] [2] [30569/7f8d140009c0] Invalid entry (failed to match regex): SZ-TEST-RD01 192.168.1.250 - - [19/Jan/2015:17:12:12 +0800] \"POST /common/memberLogin.jsp HTTP/1.1\" - 186 \"http://www.352.com/\" \"-\" A6pcIpAcAcAcApAcAcAcAcAc \"-\" /20150119/20150119-1712/20150119-171212-A6pcIpAcAcAcApAcAcAcAcAc 0 1433 md5:1ea05ec580f1d19564908088138d47ed
[Wed Jan 28 08:58:33 2015] [2] [30569/7f8d14000ae0] Flagging server as errored after failure to submit entry AcJcAc9cAcAcAcAcAbAcAcAc with HTTP response code 403: Forbidden
[Wed Jan 28 08:58:33 2015] [2] [30569/7f8d14000c90] Flagging server as errored after failure to submit entry lcAcAcAcAcAcAcAcAcAcAcWc with HTTP response code 403: Forbidden
[Wed Jan 28 08:58:33 2015] [2] [30569/7f8d14000e40] Flagging server as errored after failure to submit entry AcAcJcAcAcAcAXgcAcAcAcAc with HTTP response code 403: Forbidden
[Wed Jan 28 08:58:33 2015] [2] [30569/7f8d14000ed0] Flagging server as errored after failure to submit entry AcZcAcAGAcArAeAcAcAcAcAc with HTTP response code 403: Forbidden
[Wed Jan 28 08:58:33 2015] [2] [30569/7f8d140009c0] Flagging server as errored after failure to submit entry AcAcAcAwActcAMAcAUAcAcAc with HTTP response code 403: Forbidden
[Wed Jan 28 08:58:33 2015] [3] [30569/0] No more data to read, emptying buffer: End of file found
[Wed Jan 28 08:58:33 2015] [3] [30569/7f8d206d4158] Running final transaction checkpoint.
[Wed Jan 28 08:58:33 2015] [3] [30569/0] ModSecurity Audit Log Collector 2.9.0-RC2 terminating normally.

**Comment by klaubert** [comment]
Hi,

I need do test in nginx, but by now I recommend to use modsec2waffle
instead of mlogc.

Best regards,

Klaubert
Em 27/01/2015 01:14, "wangxianwei" <notifications@github.com> escreveu:

**Comment by klaubert** [comment]
Sic... mlog2waffle,

Klaubert
Em 27/01/2015 01:14, "wangxianwei" <notifications@github.com> escreveu:

**Comment by wangxianwei** [comment]
Where can I get the mlog2waffle package, should I install with the Modsecurity or the WAF-FLE?

**Comment by klaubert** [comment]
Mlog2waffle comes with waf-fle, check the ./extra/mlog2waffle directory.

Best regards,
Klaubert
Em 01/02/2015 22:28, "wangxianwei" <notifications@github.com> escreveu:

**Comment by wangxianwei** [comment]
Hi Klaubert, 
what package should i install to finish the following reqirement.
 install perl-File-Pid package (you can find the RPM on EPEL) 
 install perl-File-Tail package (you can find the RPM on EPEL) 

Regareds,
Owen

**Comment by klaubert** [comment]
Owen,

you need both packages,
you can find in
http://www.rpmfind.net/linux/rpm2html/search.php?query=perl-File-Pid
and
http://www.rpmfind.net/linux/rpm2html/search.php?query=perl-File-tail

Check your platform.

Best regards,

Klaubert

**Comment by wangxianwei** [comment]
Klaubert,
when install the the two packages. which  make a new issue. can I not install th per-File-Pid.

[root@SYSTEM-WIKI ~]# rpm -qa|grep perl-File-Pid*
[root@SYSTEM-WIKI ~]# rpm -qa|grep perl-File-Tail*
perl-File-Tail-0.99.3-21.el7.noarch
[root@SYSTEM-WIKI ~]# yum install perl-File-Pid*
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: mirrors.yun-idc.com
 * epel: mirrors.ustc.edu.cn
 * extras: mirrors.163.com
 * updates: mirrors.163.com
No package perl-File-Pid* available.
Error: Nothing to do
[root@SYSTEM-WIKI ~]# cd /opt
[root@SYSTEM-WIKI opt]# rpm -ivh perl-File-Pid-1.01-14.fc21.noarch.rpm 
warning: perl-File-Pid-1.01-14.fc21.noarch.rpm: Header V3 RSA/SHA256 Signature, key ID 95a43f54: NOKEY
error: Failed dependencies:
	perl(:MODULE_COMPAT_5.18.2) is needed by perl-File-Pid-1.01-14.fc21.noarch
[root@SYSTEM-WIKI opt]#
