### ISSUE TITLE
 	HTTP 500 due to query error - table not found

### ISSUE THREAD

**Issue by pedrohc** [klaubert/waf-fle#31]
What steps will reproduce the problem?
1.Install waf-fle and MySQL server to same machine (VM).
2.Access remotely from other machine.
3.Do the setup normally.
4.Try to login.

I'm expect the login page to open but instead the server gives me a HTTP 500 error like this one ($Debug = true;):

HTTP/1.1 500 Internal Server Error Error (DatabaseVersion) Message: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'waffle.version' doesn't exist Error (DatabaseVersion) getTraceAsString: #0 /opt/waf-fle/functions.php(135): PDO->prepare('SELECT `waffle_...') #1 /opt/waf-fle/dashboard/login.php(20): require_once('/opt/waf-fle/fu...') #2 {main} Error in database query!

I'm using the version 0.6.4 in a Debian Jessie machine (VM). And accessing remotelly form a Debian Jessie machine.

Since it was a database error, I went to check the databases. It came out that there were no tables in waffle database. The setup was not creating the tables, only the database. I tried the setup with the root login a pass. For the client IP I tried with localhost and with the machines IP I was accessing remotely with.

**Comment by dmitrijn** [comment]
hi @pedrohc ,

you need to change path for ````$databaseSchema```` in setup.php where is located import file.
or you can create database manually and import tables from `````waffle.mysql`````

**Comment by pedrohc** [comment]
All right,

Thanks for the reply.


2015-03-26 12:07 GMT-03:00 dmitrijn <notifications@github.com>:
