### ISSUE TITLE
Install problem 

### ISSUE THREAD

**Issue by wangxianwei** [klaubert/waf-fle#32]
I cant get the setup.php page after I have input the URL:http://localhost/waf-fle/controller,which dispaly  a blank page. the Apache2 access log like this.
192.168.9.250 - - [18/Mar/2015:14:28:05 +0800] "GET /waf-fle/controller/setup.php HTTP/1.1" 404 226

the error log:
[Wed Mar 18 14:28:05.048030 2015] [:error] [pid 23770:tid 140372944611072] [client 192.168.9.250:60006] script '/usr/local/waf-fle/controller/setup.php' not found or unable to stat

**Comment by dmitrijn** [comment]
setup.php isn't in controller directory.
did you enabled `````$SETUP = true;````` in config.php? 
you need to visit localhost/waf-fle page for setup

**Comment by wangxianwei** [comment]
Hi dmitrijn
yes, I have enabled $SETUP = true in config.php.

if  i  visit localhost/waf-fle page,which display like this, but i can't find the setup.php

Index of /waf-fle

Parent Directory
ChangeLog
LICENSE
README
README.md
config.php
config.php.example
controller/
dashboard/
extra/
filter.php
filterprocessing.php
filtershow.php
footer.php
functions.php
header.php
session.php

**Comment by klaubert** [comment]
wangxianwei,

You need to setup Apache to run .php files, you can find information to do
this in pages 9-11 of
http://www.waf-fle.org/downloads/waf-fle_0.6.3-deployment_guide.pdf.

Be sure to check the whole guide, it has many useful information on Waf-Fle
setup.

Any issue let me know.

Best regards

Klaubert

**Comment by wangxianwei** [comment]
Hi Klaubert,

I have setup the Apache to run the waf-fle, i am do the as the deployment guide, which is my second time to setup the waf-fle,  but I dont know why this time I can get the setup.php.

I have test the apache2, php5, mysql is working.

**Comment by wangxianwei** [comment]
Hi Klaubert,
The issue have been solved! because I didn't include the waf-fle.conf in the httd.conf. so the Apache can't find the the waf-fle.conf configure file. because the apache was installed with the source.

Best Regards,
Owen Wang
