### ISSUE TITLE
WAF-FLE for the Nginx

### ISSUE THREAD

**Issue by wangxianwei** [klaubert/waf-fle#36]
Hi @klaubert @dmitrijn ,
Do we have the version for the Nginx, I deploy the waf-fle to receive the log from the mosecurity on nginx. the data type of  some fields are  not for fit in the events table. 

#0 /usr/local/waf-fle/controller/index.php(670): PDOStatement->execute()
#1 {main}pos2
exception 'PDOException' with message 'SQLSTATE[01000]: Warning: 1265 Data truncated for column 'a_client_ip_cc' at row 1' in /usr/local/waf-fle/controller/index.php:670

exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'f_content_length' at row 1' in /usr/local/waf-fle/controller/index.php:670

although I can get  the data from the mlogc and write them in the events table, but  I have change too many data types of events table, the data can not display in the event web page.

any advice is appreciated!

**Comment by dmitrijn** [comment]
@wangxianwei ,

you can try to change alters for events table:

`````
mysql> use waffle;
mysql> ALTER TABLE  `events` 
CHANGE  `f_protocol`  `f_protocol` CHAR( 8 ) NULL ,
CHANGE  `f_status`  `f_status` SMALLINT( 3 ) UNSIGNED NULL ,
CHANGE  `f_msg`  `f_msg` VARCHAR( 300 ) NULL ,
CHANGE  `f_content_length`  `f_content_length` INT( 10 ) UNSIGNED NULL ,
CHANGE  `f_connection`  `f_connection` VARCHAR( 16 ) NULL ,
CHANGE  `f_content_type`  `f_content_type` VARCHAR( 30 ) NULL;
mysql> quit
`````

**Comment by asd5230653** [comment]
Hello, may I ask how to install nginx on waf-fle?

**Comment by asd5230653** [comment]
Hello, may I ask how to install waf-fle on nginx?
