### ISSUE TITLE
Add new sensor -  HTTP/1.1 500 Internal Server Error 

### ISSUE THREAD

**Issue by techtinextcom** [klaubert/waf-fle#46]
Hello,
I have a CentOS with
WAF-FLE Version:    0.6.4
APC Cache extension:    Extension APCu (4.0.7) loaded, enabled and turned "on" in WAF-FLE
APC Cache Timeout:  30 seconds
PHP version:    5.5.28
PHP Zend Version:   2.5.0
MySQL Version:  5.5.45

When I try to create a sensor, I receive HTTP/1.1 500 Internal Server Error.
In the log file I have:
 Cannot modify header information - headers already sent by (output started at /usr/local/waf-fle_0.6.4/header.php:242) in /usr/local/waf-fle_0.6.4/functions.php on line 2502, referer: http://hide.me/waf-fle/management.php?New=Sensor

Any idea?

Thank you
Regards
Johny

**Comment by naxxonuy** [comment]
Any one on this issue?

**Comment by klaubert** [comment]
naxxonuy, 

you probably try to insert a new sensor with same name of an existing one.
If you need a new sensor, it must use a different name. If you would like to use same name you should use the already existing sensor.

Klaubert

**Comment by masoudqashqai** [comment]
i have the same problem when trying to create a new sensor ,there is no sensor available right now on waf-fle so it cant be using the same name for an existing sensor

**Comment by fa4fahmed15** [comment]
[Wed Jun 10 02:42:09.779006 2020] [:error] [pid 2455] [client 45.116.233.18:35488] PHP Warning:  Cannot modify header information - headers already sent by (output started at /usr/local/waf-fle/header.php:74) in /usr/local/waf-fle/functions.php on line 1535, referer: http://144.91.91.48/waf-fle/password.php?User=1
[Wed Jun 10 02:42:09.779140 2020] [:error] [pid 2455] [client 45.116.233.18:35488] PHP Warning:  Cannot modify header information - headers already sent by (output started at /usr/local/waf-fle/header.php:74) in /usr/local/waf-fle/functions.php on line 1536, referer: http://144.91.91.48/waf-fle/password.php?User=1
