### ISSUE TITLE
logs are not generated with concurrent (secAuditLogType)

### ISSUE THREAD

**Issue by coolsivakrishna** [klaubert/waf-fle#47]
Hi,

In /etc/modsecurity/modsecurity.conf file,
if I keep 
'SecAuditLogType' as 'Serial'
then it is working fine and storing the logs.

But when I change it to 'Concurrent' mode it is not storing logs
(Note: I've uncommented the 'SecAuditLogStorageDir' )

Thankyou

**Comment by klaubert** [comment]
coolsivakrishna,

How are defined the permissions of directory refered in SecAuditLogStorageDir?
Have used running Apache able to navigate and write in that directory?

Best regards,

**Comment by coolsivakrishna** [comment]
hi klaubert,

thanks for your response.

I've given those permissions to that directory.

actually when using 'Cocurrent' type, it is not storing logs in 'modsec_audit.log' file
whereas when using 'Serial' type, it is stoting logs in 'modsec_audit.log'

Thankyou.
