### ISSUE TITLE
Event Feeder Wizard is being reset everytime

### ISSUE THREAD

**Issue by coolsivakrishna** [klaubert/waf-fle#48]
Hi,

After setting all the values to event feeder wizard and changing configurations accordingly, how to save it to keep them persistent.

For me, they are being reset just after closing tab.

Thankyou.

**Comment by dmitrijn** [comment]
what event feeder you're using? mlogc\mlog2waffle?
i recommend to use mlog2waffle it's running as a service and working just fine
if you choose mlog2waffle copy\paste configuration from wizard to your configuration file and install package dependencies on sensor machine.

**Comment by klaubert** [comment]
As Dmitri had written, event feeder wizard configurations must be
copy/paste on your modsecurity server, its just a template.

Klaubert
Em 07/09/2015 5:09 AM, "dmitrijn" notifications@github.com escreveu:
